title: Dungeon World en galego
description: Texto de referencia básico de Dungeon World en galego
remote_theme: just-the-docs/just-the-docs

heading_anchors: true
permalink: /:slug

back_to_top: true
back_to_top_text: "Volver arriba"
